# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    vsVersion: '2019'

- script: |
    dotnet sitecore condition: --help
  displayName: 'XM CLoud Sitecore help'

- script: echo Hello, world!
  displayName: 'Upload to the environment'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    dotnet sitecore --help
  displayName: 'Run a multi-line script'
